### PR TITLE
Initialize Quill on a digest cycle after component initialization

### LINKED ISSUE #94: ng-attr-title not working on select tags with ng-quill and a custom toolbar?
but is working with vanilla quill and a custom toolbar...

Hover over Bold on each. ng-attr title works.
Hover over Alignment, it uses ng-attr-title and is only working with vanilla quill.
Hover over Alignment2, it uses a regular title and works on both.

http://jsbin.com/yumifabexa/edit?html,js,output

### PR DESCRIPTION
**Pull request by jziggas**
This fixes #94 by wrapping the Quill initialization in a `$scope.$applyAsync()` and deferring the rest of the `$postLink` logic until the next digest cycle has completed. 

The `this` context was lost within the `then` handler so I adopted the [Angular style guide's](https://github.com/johnpapa/angular-styleguide/blob/master/a1/README.md#controlleras-with-vm) practice of using `var vm = this` to save the controller context. As a result the `bind` calls are no longer necessary. I suppose I could have kept using `bind`s but IMO this is way easier to read. Hope you don't mind.

### CODE REVIEW

**Comment by jziggas** [comment]
FYI This also fixed the issue I was having where dynamically setting toolbar IDs was throwing errors via `ng-attr-id`.

**Comment by KillerCodeMonkey** [comment]
i added some comments to the files.. it is late here and so on.. maybe i am missing something. But i hope it makes sense :D. If you have questions or problems to change something --> let me know and we will dig this out together.

And thank you very much for your work and help!

**Comment by jziggas** [comment]
Errr.. I'm not seeing comments anywhere in the 'Files Changed' tab? Where do I look? Yeah I know there is a large time difference. Respond at your convenience.

**Comment by KillerCodeMonkey** [comment]
sorry, i forgot to click on "submit review" -.-"

**Comment by KillerCodeMonkey** [comment]
@jziggas check release 2.3.0

**Pull request closed without merging**
