### PR TITLE
added font-whitelist and size-whitelists params

### PR DESCRIPTION
**Pull request by DenniLa2**
Hello!
I added params to import font white list and size white list

### CODE REVIEW

**Comment by DenniLa2** [comment]
fix: changed const to var

**Comment by KillerCodeMonkey** [comment]
you do not need this options... simply use the customOptions ;), there you can pass an array of imports and whitelists.

check: http://killercodemonkey.github.io/ng-quill/demo.html the "custom font sizes" example.

close this PR if this fullfils your needs.

**Comment by DenniLa2** [comment]
@KillerCodeMonkey I don`t see "customOptions" and don`t understand how i can use it, sorry. I also don`t see the "custom font size" example. Sorry again ))

**Comment by KillerCodeMonkey** [comment]
Simply open readme in master and check latest bullet point in confiuration
block. And for an example open demo.html in master branch. There you see
customOptions setting and how to pass the values to the editor. Hope that
clears it out

Am 27.11.2017 10:25 nachm. schrieb "Denni" <notifications@github.com>:

**Comment by DenniLa2** [comment]
@KillerCodeMonkey hello!
All work fine, thanks!
Best regards

**Pull request closed without merging**
